#!/usr/bin/bash

FREQLIST=($(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies))  
FREQMIN=${FREQLIST[-1]} 
FREQMAX=${FREQLIST[1]} 
case $1 in
	on|1)
		val=1
		freq=$FREQMAX
		;;
	off|0)
		val=0
		freq=$FREQMIN
		;;
	*)
		exit 1
		;;
esac

echo "echo $val > /sys/devices/system/cpu/cpufreq/boost"
echo $val > /sys/devices/system/cpu/cpufreq/boost
echo "cpupower frequency-set --min $freq"
cpupower frequency-set --max $freq
